# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "Zoé Miller"

### Header
header:
  logo:
    image: "assets/img/짱구.png"
    alt: "최경준"

### Social
social:
  - title: "Github"
    icon: "fab fa-github"
    url: "https://github.com/choi-gj"

  - title: LinkedIn"
    icon: "fab fa-LinkedIn"
    url: "https://linkedin.com/in/choigj"

  - title: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/choi-gj"

### Footer
footer:
  developer: "개발자 - 최경준"
  copyright: "웹 포트폴리오. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "UI UX Design"
      slug: "ui-ux-design"

    - name: "Photography"
      slug: "photography"

    - name: "Development"
      slug: "development"

    - name: "Branding"
      slug: "branding"
