# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: "최경준"

### Header
header:
  logo:
    image: "assets/img/logo.png"
    alt: "최경준"

### Social
social:
  - title: "Github"
    icon: "fab fa-github"
    url: "https://github.com/choi-gj"

  - title: LinkedIn"
    icon: "fab fa-LinkedIn"
    url: "https://linkedin.com/in/choigj"

  - title: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/choi-gj"

### Footer
footer:
  developer: "개발자 - 최경준"
  copyright: "웹 포트폴리오. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "grid" # 옵션: "grid" 또는 "list"
  filters:
    - name: "웹 개발"
      slug: "web-development"

    - name: "앱 개발"
      slug: "app-development"

    - name: "UI/UX 디자인"
      slug: "ui-ux-design"

    - name: "브랜딩"
      slug: "branding"
